#app-web-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  labels:
    app: edith
spec:
  selector:
    matchLabels:
      app: edith
      tier: web
  template:
    metadata:
      labels:
        app: edith
        tier: web
    spec:
      containers:
      - name: edith-app
        image: piposun/edith:1.0
        ports:
        - containerPort: 8080

---
#app-web-service
apiVersion: v1
kind: Service
metadata:
  name: app-web
  labels:
    app: edith
    tier: app-web
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: edith
    tier: app-web

---
#redis-master controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  selector:
    matchLabels:
      app: edith
      tier: web
  template:
    metadata:
      labels:
        app: edith
        tier: web
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
---
#redis-master service
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend