#app-web-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  labels:
    app: edith
spec:
  selector:
    matchLabels:
      app: edith
      tier: web
  template:
    metadata:
      labels:
        app: edith
        tier: web
    spec:
      containers:
      - name: edith-app
        image: piposun/edith:1.0
        ports:
        - containerPort: 8080

---
#app-web-service
apiVersion: v1
kind: Service
metadata:
  name: app-web
  labels:
    app: edith
    tier: app-web
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: edith
    tier: app-web

---
#redis-master controller
apiVersion: v1
kind: Deployment
metadata:
  name: redis-master
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: redis
    role: master
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: edith
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
#redis-master service
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend