pipeline {
    agent any
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        
        stage ('Docker Build/Push Image on GCR') {
            steps {
                sh 'gcloud container builds submit --tag gcr.io/edith-259213/retwis-image:1.0 .'
            }
        }
        
        stage ('Finished'){
           steps{
				sh 'echo "Hello World"'
           }
        }
    }
}