pipeline {
    agent any
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage ('Docker build'){
        	steps{
        	    sh 'docker build . -t piposun/edith:1.0'
        	}
        }
        stage ('Docker push'){
            steps{
        	    sh 'docker push piposun/edith:1.0'
        	}   
        }
        stage ('Finished'){
           steps{
				sh 'echo "Hello World"'
           }
        }
    }
}