pipeline {
   agent any

   stages {
      stage('Test') {
         steps {
         
	         try {
	  		 echo " BRANCH_NAME=$BRANCH_NAME"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }  
         
         
	         try {
	  		 echo " CHANGE_ID=$CHANGE_ID"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }   
           
	 try {
	  		 echo " CHANGE_URL=$CHANGE_URL"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }  
         
	            try {
	  		 echo " CHANGE_TITLE=$CHANGE_TITLE"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }  
         
	           try {
	  		 echo " CHANGE_AUTHOR=$CHANGE_AUTHOR"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }   
         
	         try {
	  		 echo " CHANGE_TARGET=$CHANGE_TARGET"
	         }
	  	     catch (MissingPropertyException e) {
	          
	         }  
         
         }
      }
   }
}